elk:
  image: sebp/elk
  hostname: elasticsearch
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    - "5000:5000"
  volumes:
    - './logstash.conf:/etc/logstash/conf.d/03-tcp.conf'