spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: false
  boot:
    admin:
      context-path: /admin 
server:
  port: 8761
eureka:
  instance:    hostname: localhost
  client:    register-with-eureka: false
    fetch-registry: true
    service-url:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:    wait-time-in-ms-when-sync-empty: 5
management:
  metrics:
    export:
      elastic:
        enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - "*"
  endpoint:
    loggers:
      enabled: true
  health:
    ldap:
      enabled: false
