eureka:
  instance:
    hostname: preprod
    # hostname: localhost - SPP 25.2.2022 changed to preprod
    # hostname: preprodser.dashboard.ap.bps.uk.atos.net
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    # note that this is the OTHER Eureka instance. If more than one Eureka list all of them
    # here seperated by a , such as: http://eureka1,http://eureka2 
      # defaultZone: http://preprods.dashboard.ap.bps.uk.atos.net:8761/eureka/
      # SPP 25.02.2020 - Replaced below  2 lines with simpler approach that works in 2 node setup
      # defaultZone: http://localhost:8761/eureka/
      # additionalZones: http://10.43.216.139:8761/eureka/
      # SPP/PKB - Set to the other eureka server
      defaultZone: http://10.43.216.139:8761/eureka/

atos:
  logstash:
    url: 10.43.192.208:5000